CREATE INDEX idx_sessao_status
ON SESSAO (STATUS);

CREATE INDEX idx_sessao_cliente
ON SESSAO (ID_CLIENTE);

CREATE INDEX idx_sessao_computador
ON SESSAO (ID_COMPUTADOR);

CREATE INDEX idx_cliente_email
ON CLIENTE (EMAIL);

SHOW INDEX FROM SESSAO;
SHOW INDEX FROM CLIENTE;