DELIMITER $$

CREATE TRIGGER trg_valida_estoque
BEFORE INSERT ON CONSUMO_PRODUTO
FOR EACH ROW
BEGIN
    DECLARE v_estoque INT;

    SELECT QUANTIDADE_ESTOQUE INTO v_estoque
    FROM PRODUTO
    WHERE ID_PRODUTO = NEW.ID_PRODUTO;

    IF v_estoque < NEW.QUANTIDADE THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Estoque insuficiente para a venda.';
    END IF;
END$$

CREATE TRIGGER trg_atualiza_estoque
AFTER INSERT ON CONSUMO_PRODUTO
FOR EACH ROW
BEGIN
    UPDATE PRODUTO
    SET QUANTIDADE_ESTOQUE = QUANTIDADE_ESTOQUE - NEW.QUANTIDADE
    WHERE ID_PRODUTO = NEW.ID_PRODUTO;
END$$

CREATE TRIGGER trg_auditoria_sessao
AFTER UPDATE ON SESSAO
FOR EACH ROW
BEGIN
    IF OLD.STATUS = 'ABERTA' AND NEW.STATUS = 'FECHADA' THEN
        INSERT INTO AUDIT_LOG (
            DATA_HORA,
            TABELA_AFETADA,
            ID_REGISTRO,
            ACAO,
            DESCRICAO,
            ID_CLIENTE
        )
        VALUES (
            NOW(),
            'SESSAO',
            NEW.ID_SESSAO,
            'UPDATE',
            CONCAT('Sessão ', NEW.ID_SESSAO, ' encerrada - cliente ', NEW.ID_CLIENTE),
            NEW.ID_CLIENTE
        );
    END IF;
END$$

DELIMITER ;