CREATE VIEW vw_sessoes_ativas AS
SELECT
    s.ID_SESSAO,
    c.NOME AS CLIENTE,
    s.ID_COMPUTADOR,
    s.ENTRADA,
    TIMESTAMPDIFF(MINUTE, s.ENTRADA, NOW()) AS MINUTOS_EM_USO
FROM SESSAO s
JOIN CLIENTE c ON c.ID_CLIENTE = s.ID_CLIENTE
WHERE s.STATUS = 'ABERTA';

CREATE VIEW vw_ranking_clientes AS
SELECT
    c.ID_CLIENTE,
    c.NOME,
    COUNT(s.ID_SESSAO) AS TOTAL_SESSOES,
    COALESCE(SUM(s.VALOR_TOTAL), 0) AS TOTAL_GASTO,
    COALESCE(AVG(s.VALOR_TOTAL), 0) AS MEDIA_GASTO
FROM CLIENTE c
LEFT JOIN SESSAO s ON s.ID_CLIENTE = c.ID_CLIENTE
GROUP BY c.ID_CLIENTE, c.NOME
ORDER BY TOTAL_GASTO DESC;

CREATE VIEW vw_produtos_mais_vendidos AS
SELECT
    p.NOME,
    p.CATEGORIA,
    SUM(cp.QUANTIDADE) AS TOTAL_VENDIDO,
    SUM(cp.QUANTIDADE * p.PRECO) AS RECEITA_TOTAL
FROM PRODUTO p
JOIN CONSUMO_PRODUTO cp ON cp.ID_PRODUTO = p.ID_PRODUTO
GROUP BY p.ID_PRODUTO, p.NOME, p.CATEGORIA
ORDER BY TOTAL_VENDIDO DESC;