# Estrutura Física do Banco de Dados (DDL)

Abaixo estão os comandos SQL responsáveis pela criação das tabelas do sistema.

## Criação do Banco de Dados

```sql
CREATE DATABASE LAN_HOUSE;
USE LAN_HOUSE;
```

---

## Tabela CLIENTE

```sql
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    SEXO CHAR(1) NOT NULL,

    CONSTRAINT CHK_SEXO_CLIENTE
        CHECK (SEXO IN ('M', 'F', 'O'))
);
```

---

## Tabela TELEFONE

```sql
CREATE TABLE TELEFONE (
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(15) NOT NULL,

    ID_CLIENTE INT NOT NULL,

    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
);
```

---

## Tabela COMPUTADOR

```sql
CREATE TABLE COMPUTADOR (
    ID_COMPUTADOR INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(20) NOT NULL,

    CONSTRAINT CHK_STATUS_COMPUTADOR
        CHECK (STATUS IN ('LIVRE', 'OCUPADO', 'MANUTENCAO'))
);
```

---

## Tabela HARDWARE

```sql
CREATE TABLE HARDWARE (
    ID_HARDWARE INT PRIMARY KEY AUTO_INCREMENT,
    PLACA_MAE VARCHAR(50) NOT NULL,
    PROCESSADOR VARCHAR(50) NOT NULL,
    PLACA_VIDEO VARCHAR(50) NOT NULL,
    MEMORIA_RAM VARCHAR(30) NOT NULL,
    ARMAZENAMENTO VARCHAR(30) NOT NULL,
    FONTE VARCHAR(40) NOT NULL,

    ID_COMPUTADOR INT NOT NULL,

    FOREIGN KEY (ID_COMPUTADOR)
        REFERENCES COMPUTADOR(ID_COMPUTADOR)
);
```

---

## Tabela SESSAO

```sql
CREATE TABLE SESSAO (
    ID_SESSAO INT PRIMARY KEY AUTO_INCREMENT,
    ENTRADA DATETIME NOT NULL,
    SAIDA DATETIME,

    ID_CLIENTE INT NOT NULL,
    ID_COMPUTADOR INT NOT NULL,

    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),

    FOREIGN KEY (ID_COMPUTADOR)
        REFERENCES COMPUTADOR(ID_COMPUTADOR)
);
```

---

## Tabela TORNEIO

```sql
CREATE TABLE TORNEIO (
    ID_TORNEIO INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,

    CONSTRAINT CHK_STATUS_TORNEIO
        CHECK (STATUS IN ('ABERTO', 'EM_ANDAMENTO', 'FINALIZADO'))
);
```

---

## Tabela FORMA_PAGAMENTO

```sql
CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_PAGAMENTO VARCHAR(20) NOT NULL,

    CONSTRAINT CHK_TIPO_PAGAMENTO
        CHECK (TIPO_PAGAMENTO IN ('PIX', 'DINHEIRO', 'CREDITO', 'DEBITO'))
);
```

---

## Tabela INSCRICAO

```sql
CREATE TABLE INSCRICAO (
    ID_INSCRICAO INT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(10,2) NOT NULL,

    CONSTRAINT CHK_VALOR_INSCRICAO
        CHECK (VALOR >= 0),

    DATA_PAGAMENTO DATE NOT NULL,

    ID_CLIENTE INT NOT NULL,
    ID_TORNEIO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,

    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),

    FOREIGN KEY (ID_TORNEIO)
        REFERENCES TORNEIO(ID_TORNEIO),

    FOREIGN KEY (ID_FORMA_PAGAMENTO)
        REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);
```

---

## Tabela PRODUTO

```sql
CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DATA_VALIDADE DATE NOT NULL
);
```

---

## Tabela CONSUMO

```sql
CREATE TABLE CONSUMO (
    ID_CONSUMO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,

    ID_SESSAO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,

    CONSTRAINT CHK_PRECO_CONSUMO
        CHECK (PRECO >= 0),

    FOREIGN KEY (ID_SESSAO)
        REFERENCES SESSAO(ID_SESSAO),

    FOREIGN KEY (ID_FORMA_PAGAMENTO)
        REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);
```

---

## Tabela CONSUMO_PRODUTO

```sql
CREATE TABLE CONSUMO_PRODUTO (
    ID_PRODUTO INT NOT NULL,
    ID_CONSUMO INT NOT NULL,

    PRIMARY KEY (ID_PRODUTO, ID_CONSUMO),

    FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTO(ID_PRODUTO),

    FOREIGN KEY (ID_CONSUMO)
        REFERENCES CONSUMO(ID_CONSUMO)
);
```

---

## Tabela AUDIT_LOG

```sql
CREATE TABLE AUDIT_LOG (
    ID_AUDIT INT PRIMARY KEY AUTO_INCREMENT,
    DATA_HORA DATETIME NOT NULL,
    TABELA_AFETADA VARCHAR(30) NOT NULL,
    ID_REGISTRO INT NOT NULL,
    ACAO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,

    ID_CLIENTE INT,

    CONSTRAINT CHK_ACAO_AUDIT
        CHECK (ACAO IN ('UPDATE', 'DELETE', 'INSERT')),

    FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
);
```
